---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: application-service
  namespace: application-service
spec:
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: namespaces
  - group: ""
    resource: configmaps
  - group: appstudio.redhat.com
    identityHash: 9db947d01c556d42569c6feb28eff8227373633596c47e7d1d0529286fb4c5a9
    resource: applications
  - group: appstudio.redhat.com
    identityHash: 9db947d01c556d42569c6feb28eff8227373633596c47e7d1d0529286fb4c5a9
    resource: applicationsnapshots
  - group: appstudio.redhat.com
    identityHash: 9db947d01c556d42569c6feb28eff8227373633596c47e7d1d0529286fb4c5a9
    resource: applicationsnapshotenvironmentbindings
  - group: appstudio.redhat.com
    identityHash: 9db947d01c556d42569c6feb28eff8227373633596c47e7d1d0529286fb4c5a9
    resource: components
  - group: appstudio.redhat.com
    identityHash: 9db947d01c556d42569c6feb28eff8227373633596c47e7d1d0529286fb4c5a9
    resource: componentdetectionqueries
  - group: appstudio.redhat.com
    identityHash: 9db947d01c556d42569c6feb28eff8227373633596c47e7d1d0529286fb4c5a9
    resource: environments
  - group: appstudio.redhat.com
    identityHash: 3cf25716cf24b1cd9621daa945e7ccba0688425e21bdd6972ce42018f7cab974
    resource: spiaccesstokens
  - group: appstudio.redhat.com
    identityHash: 3cf25716cf24b1cd9621daa945e7ccba0688425e21bdd6972ce42018f7cab974
    resource: spiaccesstokenbindings
