# permissions for end users to view frontends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frontend-viewer-role
  labels: 
    rbac.authorization.k8s.io/aggregate-to-view: "true"

rules:
- apiGroups:
  - cloud.redhat.com
  resources:
  - frontends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.redhat.com
  resources:
  - frontends/status
  verbs:
  - get
