# permissions for end users to edit frontends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frontend-editor-role
  labels: 
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    managed.openshift.io/aggregate-to-dedicated-admins: "cluster"
rules:
- apiGroups:
  - cloud.redhat.com
  resources:
  - frontends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.redhat.com
  resources:
  - frontends/status
  verbs:
  - get
