apiVersion: cloud.redhat.com/v1alpha1
kind: FrontendEnvironment
metadata:
  name: env-boot 
spec:
  sso: 'https://env-boot-751imhwx-auth.apps.appstudio-demo.76oz.p1.openshiftapps.com/auth/'
  ingressClass: openshift-default
  hostname: env-boot-751imhwx.apps.appstudio-demo.76oz.p1.openshiftapps.com
   