apiVersion: cloud.redhat.com/v1alpha1
kind: FrontendEnvironment
metadata:
  name: env-boot 
spec:
  sso: 'https://env-boot-uxu8263x-auth.apps.ci-ln-m7200b2-72292.origin-ci-int-gce.dev.rhcloud.com/auth/'
   