apiVersion: cloud.redhat.com/v1alpha1
kind: FrontendEnvironment
metadata:
  name: env-boot 
spec:
  sso: 'https://env-boot-5h8d1n5p-auth.apps-crc.testing/auth/'
  ingressClass: openshift-default
  hostname: env-boot-local-127-0-0-1.nip.io
   