resources:
- https://github.com/redhat-appstudio/application-service/config/kcp?ref=479ab47a47d677f2127a19504e6ac655cb2ab0d5

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/application-service
  newName: quay.io/redhat-appstudio/application-service
  newTag: 479ab47a47d677f2127a19504e6ac655cb2ab0d5

namespace: application-service

patchesStrategicMerge:
- ./manager_resources_patch.yaml

patches:
- patch: |-
    - op: add
      path: /metadata/labels/appstudio.redhat.com~1namespacetype
      value:
        "controller"
    - op: add
      path: /metadata/annotations/k8s.ovn.org~1acl-logging
      value:
        '{"deny": "info", "allow": "info"}'
  target:
    kind: Namespace
    